preferred_syntax = :scss
http_path = '/'
css_dir = 'app/css'
sass_dir = 'src/sass'
images_dir = 'src/images'
javascripts_dir = 'src/js'
relative_assets = true
line_comments = true
# output_style = :compressed